### PR TITLE
Update script for Ubuntu 16.04, and fix issues

### PR DESCRIPTION
**Pull request by PanisSupraOmnia**
This works better than what's in the repo right now, but it's still running into a few perms issues at the very end, with [PostgreSQL](http://pastebin.com/8XBUzjZt).

This should fix
- #3 
- #4 
- #5

### CODE REVIEW

**Comment by PanisSupraOmnia** [comment]
After testing it some more I've realized that something about the RVM section is critically wrong, because the script will run through the installation portion of it every time that the script is run (even if the RVM section completes successfully on a previous run). So, this PR should not be merged just yet.

**Comment by jvperrin** [comment]
You shouldn't need the RVM section at all, since Ruby 2.3.0 is the version installed by default on Ubuntu 16.04 in the package archives. I think you can replace it all with `sudo apt-get install ruby` honestly.

**Comment by PanisSupraOmnia** [comment]
Hm, correct me if I'm wrong, but it seems that if it's installed from APT then we're going to run into problems with gem: `ERROR:  While executing gem ... (Gem::FilePermissionError) You don't have write permissions for the /var/lib/gems/2.3.0 directory.` To get around this we'll either have to sudo gem (which is obviously terrible practice) or chown it, which might cause a whole host of other perms problems, or we can go back to using RVM or maybe switch to rbenv. Thoughts?

**Comment by PanisSupraOmnia** [comment]
Actually, another option would be to set it to use the `--user-install` flag every time `gem install` is used. I'm testing that out on [this branch](https://github.com/ChallahuAkbar/ubuntu-16.04-setup/tree/test-1), and it seems to be working better, though I still need to make the script set `--user-only` to be the default for `gem install`.

**Comment by jvperrin** [comment]
@ChallahuAkbar Nice, that works a lot better for installing gems. I agree installing them system-wide is a bad idea, so that works much better.

**Pull request merged**
